import unittest

from tools.update_item_catalog import parse_catalog


class ItemCatalogGeneratorTests(unittest.TestCase):
    @staticmethod
    def _html(version="0.221.12", count=300):
        rows = []
        for index in range(count):
            rows.append(
                "<tr>"
                f"<td>Prefab{index}<br><img src='Prefab{index}.png'></td>"
                f"<td>asset{index}</td>"
                f"<td>$item_{index}</td>"
                f"<td>Display {index}</td>"
                "<td>Material</td>"
                "<td>Description</td>"
                "</tr>"
            )
        return (
            "<html><body>"
            f"<p>This file is automatically generated from Valheim {version} using JotunnDoc.</p>"
            "<table><tr><th>Item</th><th>AssetID</th><th>Token</th><th>English Name</th>"
            "<th>Type</th><th>Description</th></tr>"
            + "".join(rows)
            + "</table></body></html>"
        )

    def test_parses_versioned_selectable_catalog(self):
        catalog = parse_catalog(self._html(), "https://example.invalid/items", "0.221.12")
        self.assertEqual(catalog["game_version"], "0.221.12")
        self.assertEqual(catalog["item_count"], 300)
        self.assertEqual(catalog["selectable_item_count"], 300)
        self.assertEqual(catalog["items"][0]["prefab"], "Prefab0")

    def test_refuses_unreviewed_game_version_change(self):
        with self.assertRaisesRegex(RuntimeError, "reports Valheim 1.0.0"):
            parse_catalog(self._html(version="1.0.0"), "https://example.invalid/items", "0.221.12")

    def test_refuses_suspiciously_small_catalog(self):
        with self.assertRaisesRegex(RuntimeError, "suspiciously small catalog"):
            parse_catalog(self._html(count=20), "https://example.invalid/items", "0.221.12")

    def test_a_jotunndoc_catalogue_never_overwrites_schema_2(self):
        import json
        import tempfile
        from pathlib import Path
        from unittest.mock import patch
        import tools.update_item_catalog as tool

        with tempfile.TemporaryDirectory() as tmp:
            output = Path(tmp) / "valheim_items.json"
            output.write_text(json.dumps({"schema_version": 2, "items": []}), encoding="utf-8")
            before = output.read_bytes()
            with patch.object(tool, "fetch_text", return_value=self._html()):
                self.assertEqual(tool.main(["--output", str(output), "--expected-version", "0.221.12"]), 1)
            self.assertEqual(output.read_bytes(), before)


if __name__ == "__main__":
    unittest.main()
